extends SceneTree
## v103 bounded canonical transaction and actual inventory-dialog acceptance.
## Sources are generated by the current catalog, then admitted and persisted by
## the real model. V103_TRANSACTION_CASE selects only an affected retry section.
const Model = preload("res://scripts/canonical_game_state.gd")
const Craft = preload("res://scripts/items/crafting_rules.gd")
const Planner = preload("res://scripts/items/crafting_transaction_planner.gd")
const Gear = preload("res://scripts/items/equipment_catalog.gd")
const Items = preload("res://scripts/items/unified_item_catalog.gd")
const Rules = preload("res://scripts/save/canonical_build_rules.gd")
const Locations = preload("res://scripts/items/item_location_rules.gd")
const TARGETS = {
	"targeted_reforge_fire_resistance": ["emberward", "ring_emberward"],
	"targeted_reforge_cold_resistance": ["rimeward", "ring_rimeward"],
	"targeted_reforge_lightning_resistance": ["stormward", "ring_stormward"],
	"targeted_reforge_chaos_resistance": ["ring_voidward"],
}
const LEGAL_BASES = ["emberhide_vest", "nine_slot_etched_ring"]
class FaultModel extends Model:
	var fail_save := false
	func _write_bytes(path: String, bytes: PackedByteArray) -> Error:
		return ERR_CANT_CREATE if fail_save else super._write_bytes(path, bytes)
var checks := 0
var failures := 0
var serial := 0
var changes := 0
var completed := false
var generation_cache := {}
var report := {"sections": {}, "failures": [], "metadata": [], "transactions": [], "boundaries": []}
var output_dir := ""

func _initialize() -> void: call_deferred("run")
func check(value: bool, label: String) -> bool:
	checks += 1
	if not value:
		failures += 1
		report.failures.append(label)
		push_error(label)
	return value
func near(actual: float, expected: float, label: String) -> bool:
	return check(is_finite(actual) and absf(actual - expected) < 1e-8, "%s: %s == %s" % [label, actual, expected])
func accepted(result: Dictionary, label: String) -> bool:
	return check(result.get("ok", false), label + ": " + JSON.stringify(result))
func rejected(result: Dictionary, code: String, label: String) -> bool:
	return check(not result.get("ok", true) and result.get("code", "") == code
		and not str(result.get("reason", "")).is_empty() and result.size() == 3,
		label + ": " + JSON.stringify(result))
func valid_target(source: Dictionary, operation: String) -> bool:
	return source.affixes.any(func(a: Dictionary) -> bool: return TARGETS[operation].has(a.id))
func legal_target(base: String, operation: String) -> bool:
	return base == "nine_slot_etched_ring" or (base == "emberhide_vest" and operation != "targeted_reforge_chaos_resistance")
func entry(rows: Array, operation: String) -> Dictionary:
	for row: Dictionary in rows:
		if row.operation == operation: return row
	return {}

func generated(uid: String, base: String, rarity: String, absent_target: String = "") -> Dictionary:
	var key := base + ":" + rarity + ":" + absent_target
	if not generation_cache.has(key):
		var pool := Gear.current_pool_for_base(base)
		for offset: int in range(2048):
			var rng := RandomNumberGenerator.new()
			rng.seed = 103000 + offset
			var source := Gear.generate_for_pool(rng, uid, Gear.MAX_ITEM_LEVEL, rarity, pool)
			if source.is_empty() or source.base_id != base: continue
			if not absent_target.is_empty() and valid_target(source, absent_target): continue
			if not absent_target.is_empty() and rarity == "rare" and source.affixes.size() != 6: continue
			generation_cache[key] = {"source": source, "seed": 103000 + offset, "pool": pool}
			break
	if not check(generation_cache.has(key), "Bounded catalog generation finds " + key): return {}
	var record: Dictionary = generation_cache[key].duplicate(true)
	record.source.id = uid
	check(Gear.validate_instance_for_version(record.source, Gear.CURRENT_VOCABULARY), "Generated source passes current vocabulary")
	return record

func fixture(base: String, rarity: String = "magic", operation: String = "", funds: int = 100) -> Dictionary:
	serial += 1
	var model := FaultModel.new()
	var record := generated("gear_%06d" % int(model.snapshot().next_item_serial), base, rarity, operation)
	if record.is_empty(): return {}
	if not check(model._admit_reward_item(Items.wrap_equipment(record.source)), "Admit lawful generated source UID"): return {}
	var stacks: Array[String] = []
	for quantity: int in [1, funds - 1]:
		if quantity <= 0: continue
		var uid := "item_%06d" % int(model.snapshot().next_item_serial)
		if not check(model._admit_reward_item(Items.calibration_shard(uid, quantity)), "Admit real shard stack"): return {}
		stacks.append(uid)
	var path := "user://v103-resistance-%03d.json" % serial
	if not check(Rules.reason(model.snapshot()).is_empty() and model.save_build(path) == OK, "Persist complete lawful current-schema source"): return {}
	return {"model": model, "source": record.source, "generation": record, "path": path, "stacks": stacks}

func mark(f: Dictionary) -> Dictionary:
	return {"state": var_to_bytes(f.model.snapshot()), "disk": FileAccess.get_file_as_bytes(f.path),
		"attempts": f.model.save_attempts, "saves": f.model.successful_saves}
func unchanged(f: Dictionary, before: Dictionary, label: String, extra_attempts: int = 0) -> bool:
	return check(var_to_bytes(f.model.snapshot()) == before.state and FileAccess.get_file_as_bytes(f.path) == before.disk
		and f.model.save_attempts == before.attempts + extra_attempts and f.model.successful_saves == before.saves,
		label + ": exact state, UID, currency, serial, crafting seed revision and disk remain unchanged")
func isolated_rejection(f: Dictionary, action: Callable, code: String, label: String, extra_attempts: int = 0) -> bool:
	var before := mark(f)
	seed(103019)
	var expected_rng := randi()
	seed(103019)
	var result: Dictionary = action.call()
	return rejected(result, code, label) and check(randi() == expected_rng, label + ": global RNG unchanged") and unchanged(f, before, label, extra_attempts)
func write_json(name: String, data: Variant) -> void:
	if output_dir.is_empty(): return
	var file := FileAccess.open(output_dir.path_join(name), FileAccess.WRITE)
	if not check(file != null, "Open evidence " + name): return
	file.store_string(JSON.stringify(data, "\t", true, true))
	file.close()
func export_snapshot(name: String, f: Dictionary) -> void:
	if output_dir.is_empty(): return
	var file := FileAccess.open(output_dir.path_join(name + ".save"), FileAccess.WRITE)
	if not check(file != null, "Open lawful save evidence " + name): return
	file.store_buffer(FileAccess.get_file_as_bytes(f.path))
	file.close()
	var loaded := Model.new()
	check(loaded.load_build(output_dir.path_join(name + ".save")) and Planner._same_data(loaded.snapshot(), f.model.snapshot()), "Exported save reloads through current authority: " + name)

func metadata_matrix() -> void:
	for base: String in Gear.all_base_ids():
		var rarities: Array = ["normal", "magic", "rare"] if LEGAL_BASES.has(base) else ["rare"]
		for rarity: String in rarities:
			var f := fixture(base, rarity)
			if f.is_empty(): return
			var model: FaultModel = f.model
			var before := mark(f)
			var sequence: int = model._craft_sequence
			seed(103017)
			var next_rng := randi()
			seed(103017)
			var rows := model.crafting_operations(f.source.id, f.path)
			check(randi() == next_rng and rows.size() == Craft.operation_ids().size() and rows.size() == 14, "Read-only metadata exposes six ordinary and eight targeted operations")
			check(model._craft_sequence == sequence and model._craft_quotes.is_empty(), "Metadata issues no authority")
			for operation: String in TARGETS:
				var row := entry(rows, operation)
				var available := rarity != "normal" and legal_target(base, operation)
				if not check(not row.is_empty(), "Discoverable resistance metadata"): return
				check(row.available == available and row.targeted and row.target_id == operation.trim_prefix("targeted_reforge_"), "Metadata availability and identity: " + base + "/" + rarity + "/" + operation)
				check(row.reason.is_empty() if available else not row.reason.is_empty(), "Availability explains rejection")
				check(row.cost == {Craft.MATERIAL_ID: 40 if rarity == "rare" else 16} if available else row.cost.is_empty(), "Metadata exposes authoritative exact cost")
				if not available:
					if not isolated_rejection(f, func(): return model.crafting_quote(operation, f.source.id, f.path), "unsupported_rarity" if rarity == "normal" else "no_legal_target", "Unsupported actual quote"): return
				report.metadata.append({"base": base, "rarity": rarity, "operation": operation, "entry": row})
			if not unchanged(f, before, "Metadata and unsupported quotes"): return
	completed = true

func consumers(f: Dictionary, operation: String) -> Dictionary:
	var model: FaultModel = f.model
	var uid: String = f.source.id
	var slot := "ring_1" if f.source.base_id == "nine_slot_etched_ring" else "body_armour"
	var prior: String = str(model.equipped_items().get(slot, ""))
	if not prior.is_empty():
		var destination := model.first_bag_position(prior)
		if not accepted(model.move_item(prior, destination, model.revision(), f.path), "Unequip prior gear through actual transaction"): return {}
	var before := model.get_resistance_profile()
	var chaos_before := model.get_chaos_resistance_profile()
	var crafted: Dictionary = model.item(uid).payload
	var additions: Dictionary = Gear.definition(crafted).stats
	if not accepted(model.move_item(uid, {"kind": "equipment", "slot_id": slot}, model.revision(), f.path), "Equip crafted same UID"): return {}
	var after := model.get_resistance_profile()
	var chaos_after := model.get_chaos_resistance_profile()
	for element: String in ["fire", "cold", "lightning"]:
		var raw := float(before.raw_resistances[element]) + float(additions.get(element + "_resistance", 0.0))
		near(after.raw_resistances[element], raw, "Equipped raw " + element + " includes exact catalog tick conversion")
		near(after.maximum_resistances[element], before.maximum_resistances[element], "Reforge adds no maximum " + element + " resistance")
		near(after.effective_resistances[element], clampf(raw, 0.0, float(before.maximum_resistances[element])), "Effective " + element + " uses existing cap")
	var raw_chaos := float(chaos_before.raw) + float(additions.get("chaos_resistance", 0.0))
	near(chaos_after.raw, raw_chaos, "Equipped raw chaos includes exact catalog tick conversion")
	near(chaos_after.cap, chaos_before.cap, "Reforge adds no chaos cap")
	near(chaos_after.effective, clampf(raw_chaos, 0.0, float(chaos_before.cap)), "Effective chaos uses existing cap")
	var stat := operation.trim_prefix("targeted_reforge_")
	check(float(additions.get(stat, 0.0)) > 0.0, "Actual selected resistance contributes to equipped stats")
	var restored := Model.new()
	check(restored.load_build(f.path) and Planner._same_data(restored.snapshot(), model.snapshot()), "Equipped output and all UIDs survive current-schema reload")
	check(Planner._same_data(restored.get_resistance_profile(), after) and Planner._same_data(restored.get_chaos_resistance_profile(), chaos_after), "Both current getters survive reload exactly")
	return {"before": before, "after": after, "chaos_before": chaos_before, "chaos_after": chaos_after}

func atomic_transactions() -> void:
	for base: String in LEGAL_BASES:
		for operation: String in TARGETS:
			if not legal_target(base, operation): continue
			for rarity: String in ["magic", "rare"]:
				var cost := 40 if rarity == "rare" else 16
				var f := fixture(base, rarity, operation, cost)
				if f.is_empty(): return
				var model: FaultModel = f.model
				var source: Dictionary = f.source
				var before := model.snapshot()
				var before_mark := mark(f)
				var name := base + "-" + rarity + "-" + operation.trim_prefix("targeted_reforge_")
				export_snapshot(name + "-before", f)
				var quote := model.crafting_quote(operation, source.id, f.path)
				if not accepted(quote, "Issue exact legal resistance quote"): return
				check(quote.cost == {Craft.MATERIAL_ID: cost} and quote.rules_version == Craft.operation_quote(source, operation).rules_version and quote.source_instance == source, "Quote binds current rule economics and exact source")
				check(not quote.has("seed") and not quote.has("instance") and not quote.has("candidate"), "Quote hides future result and seed")
				model.cancel_crafting_quote(quote.handle)
				if not isolated_rejection(f, func(): return model.execute_crafting(quote.handle, source), "unknown_quote", "Cancelled handle"): return
				quote = model.crafting_quote(operation, source.id, f.path)
				var actual_quote := quote.duplicate(true)
				var wrong := source.duplicate(true)
				wrong.id = "gear_999999"
				if not isolated_rejection(f, func(): return model.execute_crafting(quote.handle, wrong), "source_mismatch", "Wrong selected UID"): return
				var seed_text := JSON.stringify({"rules": Craft.seed_rules_version(operation), "revision": before.crafting.revision, "item": source}, "", true, true)
				var expected := Craft.operation_plan(source, operation, seed_text.sha256_text().substr(0, 15).hex_to_int())
				if not accepted(expected, "Derive same canonical seed candidate"): return
				changes = 0
				model.changed.connect(func(): changes += 1)
				model.fail_save = true
				if not isolated_rejection(f, func(): return model.execute_crafting(quote.handle, source), "save_failed", "Injected write failure", 1): return
				check(changes == 0 and model._craft_quotes.has(quote.handle), "Failed write retains retry authority and emits no mutation")
				model.fail_save = false
				seed(103020)
				var next_rng := randi()
				seed(103020)
				var result := model.execute_crafting(quote.handle, source)
				if not accepted(result, "Same handle retries and persists"): return
				check(randi() == next_rng, "Successful deterministic craft leaves global RNG unchanged")
				var crafted: Dictionary = model.item(source.id).payload
				var after := model.snapshot()
				check(crafted == expected.instance and Gear.validate_instance(crafted) and valid_target(crafted, operation), "Exact seeded lawful replacement guarantees selected existing family")
				check(crafted.affixes != source.affixes and not valid_target(source, operation), "All-affix replacement produces selected family absent from source")
				for field: String in ["id", "base_id", "rarity", "item_level"]: check(crafted[field] == source[field], "Craft preserves " + field)
				var exact := before.duplicate(true)
				exact.items[source.id] = Items.wrap_equipment(crafted)
				for uid: String in f.stacks:
					exact.items.erase(uid)
					exact.locations.erase(uid)
				exact.revision += 1
				exact.crafting.revision += 1
				check(Planner._same_data(after, exact) and model.crafting_balance() == 0, "Only replacement, exact actual shard debit, and two revisions change")
				check(after.version == Rules.VERSION and after.next_item_serial == before.next_item_serial and after.crafting.keys() == ["revision"], "Current schema and UID serial preserved; no new crafting ledger")
				check(changes == 1 and model.successful_saves == before_mark.saves + 1 and model.save_attempts == before_mark.attempts + 2, "Retry saves and emits exactly once")
				if not isolated_rejection(f, func(): return model.execute_crafting(quote.handle, source), "unknown_quote", "Duplicate confirmation"): return
				var reloaded := Model.new()
				check(reloaded.load_build(f.path) and Planner._same_data(reloaded.snapshot(), after), "Bag result roundtrip retains exact roll, UID, location and unrelated build")
				var profiles := consumers(f, operation)
				if profiles.is_empty(): return
				export_snapshot(name, f)
				report.transactions.append({"name": name, "operation": operation, "cost": cost, "generation": f.generation,
					"quote": actual_quote, "result": result, "crafted": crafted, "profiles": profiles,
					"presentation": Craft.operation_metadata(operation), "source_snapshot_file": name + "-before.save",
					"snapshot_file": name + ".save", "source_crafting_revision": before.crafting.revision})
	completed = true

func rejected_boundaries() -> void:
	for operation: String in TARGETS:
		for rarity: String in ["magic", "rare"]:
			var cost := 40 if rarity == "rare" else 16
			var f := fixture("nine_slot_etched_ring", rarity, operation, cost - 1)
			if f.is_empty(): return
			var model: FaultModel = f.model
			var sequence: int = model._craft_sequence
			var metadata := entry(model.crafting_operations(f.source.id, f.path), operation)
			check(not metadata.available and not metadata.reason.is_empty() and metadata.cost == {Craft.MATERIAL_ID: cost}, "Underfunded metadata preserves fee and explains deficit")
			if not isolated_rejection(f, func(): return model.crafting_quote(operation, f.source.id, f.path), "insufficient_materials", "One-shard short"): return
			check(model._craft_sequence == sequence and model._craft_quotes.is_empty(), "Rejected quote allocates no authority")
		var f := fixture("nine_slot_etched_ring", "magic", operation)
		if f.is_empty(): return
		var model: FaultModel = f.model
		if not isolated_rejection(f, func(): return model.crafting_quote(operation, "gear_999999", f.path), "not_owned", "Wrong owned UID"): return
		var quote := model.crafting_quote(operation, f.source.id, f.path)
		model.add_xp(1)
		if not isolated_rejection(f, func(): return model.execute_crafting(quote.handle, f.source), "stale_quote", "Intervening build mutation"): return
		if not check(model.save_build(f.path) == OK, "Persist intervening mutation"): return
		quote = model.crafting_quote(operation, f.source.id, f.path)
		if not accepted(model.move_item(f.source.id, {"kind": "equipment", "slot_id": "ring_1"}, model.revision(), f.path), "Equip source before craft guard"): return
		if not isolated_rejection(f, func(): return model.execute_crafting(quote.handle, f.source), "stale_quote", "Equipping invalidates old quote"): return
		if not isolated_rejection(f, func(): return model.crafting_quote(operation, f.source.id, f.path), "item_equipped", "Equipped source rejects fresh quote"): return
		var metadata := entry(model.crafting_operations(f.source.id, f.path), operation)
		check(not metadata.available and not metadata.reason.is_empty(), "Equipped metadata disabled with reason")
		f = fixture("nine_slot_etched_ring", "magic", operation)
		if f.is_empty(): return
		model = f.model
		quote = model.crafting_quote(operation, f.source.id, f.path)
		var file := FileAccess.open(f.path, FileAccess.WRITE)
		file.store_string(JSON.stringify(model.snapshot(), "  ", true, true))
		file.close()
		if not isolated_rejection(f, func(): return model.execute_crafting(quote.handle, f.source), "save_changed", "External byte rewrite"): return
		metadata = entry(model.crafting_operations(f.source.id, f.path), operation)
		check(not metadata.available and not metadata.reason.is_empty(), "Known save protection reflected by metadata")
		report.boundaries.append({"operation": operation, "passed": true})
	completed = true

func full_bag() -> void:
	var operation := "targeted_reforge_chaos_resistance"
	var f := fixture("nine_slot_etched_ring", "rare", operation)
	if f.is_empty(): return
	var model: FaultModel = f.model
	var filled := 0
	for unused: int in range(Locations.CURRENT_BAG_COLUMNS * Locations.CURRENT_BAG_ROWS * Locations.CURRENT_BAG_PAGES):
		var uid := "item_%06d" % int(model.snapshot().next_item_serial)
		if not model._admit_reward_item(Items.calibration_shard(uid, 1)): break
		filled += 1
	var before := model.snapshot()
	var layout := Locations.validate_current(Items.metadata_for_items(before.items), before.locations,
		Model.Migration.paged_location_context(before, model._socket_ids))
	check(filled > 0 and layout.ok and layout.occupied_cells.size() == Locations.CURRENT_BAG_COLUMNS * Locations.CURRENT_BAG_ROWS * Locations.CURRENT_BAG_PAGES, "All bag cells occupied by lawful owned items")
	if not check(model.save_build(f.path) == OK and Rules.reason(before).is_empty(), "Full-bag source persists lawfully"): return
	var quote := model.crafting_quote(operation, f.source.id, f.path)
	if not accepted(quote, "Full bag can quote in-place replacement"): return
	var balance := model.crafting_balance()
	if not accepted(model.execute_crafting(quote.handle, f.source), "Full bag can commit replacement without new item"): return
	check(model.crafting_balance() == balance - 40 and model.snapshot().next_item_serial == before.next_item_serial
		and model.location(f.source.id) == before.locations[f.source.id] and valid_target(model.item(f.source.id).payload, operation), "Full bag pays once, retains UID/cells, and allocates no item serial")
	report.full_bag = {"fillers": filled, "balance_before": balance, "balance_after": model.crafting_balance()}
	completed = true

func frames(count: int = 2) -> void:
	for unused in range(count): await process_frame
func request_craft(panel: Control) -> void:
	panel._craft_controls._target_button.button_down.emit()
	panel._craft_controls._target_button.pressed.emit()
	await frames()
func inventory_dialog() -> void:
	var operation := "targeted_reforge_chaos_resistance"
	var f := fixture("nine_slot_etched_ring", "rare", operation, 100)
	if f.is_empty(): return
	var arena: Node = load("res://scenes/main.tscn").instantiate()
	root.size = Vector2i(1280, 720)
	root.add_child(arena)
	arena.set_process(false)
	arena.set_physics_process(false)
	await frames(3)
	arena._replace_build(f.model, f.path)
	while arena.hud.is_blocking(): arena.hud.close_panel()
	arena.hud.open_panel("inventory")
	await frames()
	var panel: Control = arena.hud._inventory_panel
	panel._select_item(f.source.id)
	await frames()
	var controls: Control = panel._craft_controls
	var selected := -1
	for index in range(controls._target_select.item_count):
		if controls._target_select.get_item_metadata(index) == operation: selected = index
	if not check(selected >= 0, "Actual inventory discovers new chaos-resistance target"):
		arena.queue_free()
		await frames()
		return
	controls._target_select.select(selected)
	controls._target_select.item_selected.emit(selected)
	check(not controls._target_button.disabled, "Lawful funded ring enables actual target button")
	var before := mark(f)
	await request_craft(panel)
	check(panel._craft_dialog.visible and panel._pending_craft.get("quote", {}).get("operation", "") == operation, "Actual request opens one exact resistance quote")
	var confirmation: String = panel._craft_dialog.dialog_text
	check(confirmation.contains("40") and confirmation.contains("混沌抗性") and confirmation.contains("全部原词缀将被替换") and confirmation.contains("不保证高阶"), "Real dialog discloses price, target, full replacement and no tier promise")
	panel._craft_dialog.get_cancel_button().pressed.emit()
	await frames()
	check(not panel._craft_dialog.visible and panel._pending_craft.is_empty() and f.model._craft_quotes.is_empty(), "Actual Cancel clears dialog and model quote")
	unchanged(f, before, "Actual UI Cancel")
	await request_craft(panel)
	panel._craft_dialog.get_ok_button().pressed.emit()
	await frames()
	check(f.model.crafting_balance() == 60 and valid_target(f.model.item(f.source.id).payload, operation), "Actual confirm pays40 once and commits legal chaos roll")
	check(f.model.successful_saves == before.saves + 1 and f.model.save_attempts == before.attempts + 1, "Actual UI confirmation has one successful write")
	var after := mark(f)
	panel._craft_dialog.confirmed.emit()
	await frames()
	unchanged(f, after, "Actual UI duplicate confirmation")
	check(f.model.snapshot().next_item_serial == bytes_to_var(before.state).next_item_serial, "Actual UI allocates no equipment UID")
	report.inventory_dialog = {"operation": operation, "confirmation": confirmation, "source": f.source,
		"crafted": f.model.item(f.source.id).payload, "balance": f.model.crafting_balance(), "generation": f.generation}
	export_snapshot("inventory-dialog-chaos", f)
	arena.queue_free()
	await frames()
	completed = true

func run() -> void:
	if not OS.get_environment("XDG_DATA_HOME").begins_with("/tmp/godot-m1-v103-"):
		quit(78)
		return
	output_dir = OS.get_environment("V103_TRANSACTION_OUT")
	if not output_dir.is_empty(): DirAccess.make_dir_recursive_absolute(output_dir)
	report.schema = Rules.VERSION
	report.vocabulary = Gear.CURRENT_VOCABULARY
	var selected := OS.get_environment("V103_TRANSACTION_CASE")
	for test: Callable in [metadata_matrix, atomic_transactions, rejected_boundaries, full_bag, inventory_dialog]:
		if not selected.is_empty() and selected != test.get_method(): continue
		var before := checks
		var start := Time.get_ticks_msec()
		completed = false
		await test.call()
		check(completed, "Section completes normally: " + test.get_method())
		report.sections[test.get_method()] = {"checks": checks - before, "milliseconds": Time.get_ticks_msec() - start, "completed": completed}
		print("V103 section %s: %d checks, total failures %d" % [test.get_method(), checks - before, failures])
		if failures > 0: break
	report.checks = checks
	report.failure_count = failures
	write_json("transactions-report.json", report)
	print("Resistance targeted transactions: %d checks, %d failures" % [checks, failures])
	quit(0 if failures == 0 else 1)
