extends SceneTree
const Model=preload("res://scripts/canonical_game_state.gd")
func _initialize()->void:
	if Model.Rules.VERSION!=23 or ProjectSettings.get_setting("application/config/version")!="0.38.0":quit(78);return
	var directory:="res://tests/fixtures/v039_critical";DirAccess.make_dir_recursive_absolute(directory);var files:Dictionary={}
	for name:String in ["v23-default.json","v23-flasks.json"]:
		var candidate:=Model.new().snapshot()
		if name.contains("flasks"):
			candidate.revision=37;candidate.crafting.revision=11
			candidate.progress.level=119;candidate.progress.xp=17;candidate.talents.allocated=["58833","48828","33508","36881","35503","19144","16167","10829","18402"];candidate.talents.normal_points=115
		assert(Model.Rules.reason(candidate).is_empty())
		var bytes:PackedByteArray=(" \r\n"+JSON.stringify(candidate,"\t",true,true).replace("\n","\r\n")+"\r\n").to_utf8_buffer()
		var file:=FileAccess.open(directory.path_join(name),FileAccess.WRITE);file.store_buffer(bytes);file.close()
		var digest:=HashingContext.new();digest.start(HashingContext.HASH_SHA256);digest.update(bytes)
		files[name]={"bytes":bytes.size(),"sha256":digest.finish().hex_encode()}
	FileAccess.open(directory.path_join("manifest.json"),FileAccess.WRITE).store_string(JSON.stringify({"source_commit":"a4b13688c9bed0911b751854172d073e83935903","schema":23,"application_version":"0.38.0","files":files,"capture":"External export script run against unmodified source before schema24 changes; never generated by decrementing new code.","no_user_save_reads_or_writes":true},"\t",true,true))
	print("Frozen literal v23 baseline: ",files);quit()
